group: travis_latest
language: python
cache: pip

branches:
  only:
  - master

python:
  - '3.6'

before_install: &before_install
  sudo ls

install: &requirements
  pip install -r requirements.txt

jobs:
  include:
    - stage: Tests
      install:
        - *requirements
        - pip install flake8 flake8-quotes yapf
        - pip install -U pytest
      script:
        # stop the build if there are any unexpected flake8 issues
        - flake8 . --count
          --max-complexity=16
          --inline-quotes "single"
          --multiline-quotes "single"
          --docstring-quotes "double"
          --show-source --statistics
        # test to make sure the code is yapf compliant
        #- ./yapf.sh --all
        - pytest