info:
  name: mnist_pipe
  project: examples
  type: pipe
  expdir: .
pipes:
  valid:
    valid:
      type: valid
      slot: model
  infer_valid:
    infer:
      type: InferPipe
      slot: model
      suffix: valid
  infer_test:
    infer:
      type: InferPipe
      slot: model
      suffix: test
  submit:
    submit_mnist:
      type: submit_mnist
      slot: model


interfaces:
  torch:
    batch_size: 512
  equation:
    equation: ''
