info:
  name: mnist_train_stage
  project: examples
  report: classify
executors:
  train:
    type: catalyst
    gpu: 3-4
    distr: True
    single_node: True
    args:
        config: catalyst-stage.yml
