info:
  name: catalyst
  project: first
  folder: projects/catalyst
  data_folder: /f/data/first
executors:
  dummy1:
    type: Catalyst
    args:
      config: catalyst-config.yml
    series:
      - loss
      - precision01
    report:
      precision:
        type: series
        key: precision01
        multi: single
      loss:
        type: series
        key: loss
        multi: multi