info:
  name: catalyst
  project: first
  folder: projects/catalyst
  data_folder: /f/data/first
executors:
  dummy1:
    type: Catalyst
    args:
      config: catalyst-config.yml
reports:
  base:
    precision:
      type: series
      key: precision01
      multi: single
      single_group: valid
    loss:
      type: series
      key: loss
      multi: many
    precision_recall:
      type: precision_recall