info:
  name: catalyst
  project: first
  folder: projects/catalyst
  data_folder: /f/data/first
executors:
  dummy1:
    type: Catalyst
    args:
      config: catalyst-config.yml
    series:
      - loss
      - precision01
    report:
      row1:
        precision:
          type: series
          key: precision01
        loss:
          type: series
          key: loss