model_params:
  model: SimpleNet


args:
  expdir: "."
  logdir: "log"

stages:

  data_params:
    batch_size: 32
    num_workers: 1

  state_params:
    num_epochs: 10
    main_metric: &reduce_metric precision01
    minimize_metric: False
    checkpoint_data:
      exp: "thin is my best experiments"
      date: "today"

  criterion_params:
    criterion: CrossEntropyLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [10]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: LossCallback
    optimizer:
      callback: OptimizerCallback
    precision:
      callback: PrecisionCallback
      precision_args: [1]
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001