info:
  name: catalyst
  project: first
  folder: examples/catalyst
  data_folder: /f/data/first
executors:
  dummy1:
    type: Catalyst
    report: base
    args:
      config: catalyst-config.yml
reports:
  base:
    metric:
      name: precision
      minimize: False
    items:
      precision:
        type: series
        key: precision01
        multi: single
        single_group: valid
      loss:
        type: series
        key: loss
        multi: many
      precision_recall:
        type: precision_recall
      f1:
        type: f1
      img_confusion:
        type: img_confusion
        count: 10