info:
  name: catalyst
  project: catalyst
  folder: examples/catalyst
  data_folder: catalyst
executors:
  dummy1:
    type: Catalyst
    report: base
    args:
      config: catalyst-config.yml
reports:
  base:
    metric:
      name: precision
      minimize: False
    items:
      precision:
        type: series
        key: precision01
        multi: single
        single_group: valid
      loss:
        type: series
        key: loss
        multi: many
#      precision_recall:
#        type: precision_recall
#      f1:
#        type: f1
      classify:
        type: img_classify
        epoch_every: 1
        count_class_max: 5
        train: True