info:
  name: catalyst
  project: catalyst
  folder: examples/catalyst
  data_folder: catalyst
executors:
  dummy1:
    type: Catalyst
    report: classify-img
    args:
      config: catalyst-config.yml
