services:
  postgres:
    container_name: postgres
    env_file: .env
    image: postgres:11.1
    restart: always
    volumes: [
      '/opt/mlcomp/pgdata/data:/var/lib/postgresql/data/pgdata',
      '/opt/mlcomp/pgdata/backups:/backups'
    ]
    shm_size: 4G
    ports:
      - 5432:5432
  redis:
    command: 'redis-server --requirepass $REDIS_PASSWORD'
    container_name: redis
    image: redis:5.0.4
    restart: always
    ports:
      - 6379:6379
  flower:
    command: [
      "celery",
      "flower",
      "--broker=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0",
      "--port=5555"
    ]
    image: mher/flower
    container_name: flower
    restart: always
    depends_on: [redis]
    ports:
      - 5555:5555
version: '2.3'