services:
  mlcomp-server:
    container_name: mlcomp-server
    restart: always
    network_mode: "host"
    build:
      context: ../
      dockerfile: docker/server
    env_file: dev.env
  postgres:
    container_name: postgres
    env_file: dev.env
    image: postgres:11.1
    network_mode: "host"
    restart: always
    volumes: ['/opt/mlcomp/pgdata/data:/var/lib/postgresql/data/pgdata', '/opt/mlcomp/pgdata/backups:/backups']
    shm_size: 4G
  redis:
    command: 'redis-server --requirepass "$REDIS_PASSWORD"'
    env_file: dev.env
    container_name: redis
    image: redis:5.0.4
    restart: always
    network_mode: "host"
version: '2.3'