services:
  mlcomp-server:
    container_name: mlcomp-server
    restart: always
    build:
      context: ../
      dockerfile: docker/server
    env_file: dev.env
#  postgres:
#    container_name: postgres_mlcomp
#    env_file: dev.env
#    image: postgres:11.1
#    restart: always
#    volumes: ['/opt/mlcomp/pgdata/data:/var/lib/postgresql/data/pgdata', '/opt/mlcomp/pgdata/backups:/backups']
#    shm_size: 4G
#    ports:
#      - 5433:5432
#  redis:
#    command: 'redis-server --requirepass "$REDIS_PASSWORD"'
#    env_file: dev.env
#    container_name: redis
#    image: redis:5.0.4
#    restart: always
#    ports:
#      - 6379:6379
version: '2.3'