services:
  mlcomp-server:
    container_name: mlcomp-server
    restart: always
    network_mode: "host"
    build:
      context: ../
      dockerfile: docker/server-dev
  postgres:
    container_name: postgres
    environment: [POSTGRES_USER=mlcomp, POSTGRES_PASSWORD=12345,
      PGDATA=/var/lib/postgresql/data/pgdata, POSTGRES_DB=mlcomp]
    image: postgres:11.1
    network_mode: "host"
    restart: always
    volumes: ['/opt/mlcomp/pgdata/data:/var/lib/postgresql/data/pgdata', '/opt/mlcomp/pgdata/backups:/backups']
    shm_size: 4G
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-rc
    restart: always
    network_mode: "host"
  redis:
    container_name: redis
    image: redis:5.0.4
    restart: always
    network_mode: "host"
  flower:
    image: mher/flower
    network_mode: "host"
    container_name: flower
version: '3'