services:
  mlcomp-worker:
    container_name: mlcomp-worker
    restart: always
    network_mode: "host"
    build:
      context: ../
      dockerfile: docker/worker
    env_file: dev.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes: ["/opt/mlcomp/data:/opt/mlcomp/data"]
version: '2.3'