model_params:
  model: ResNetUnetSimple
  num_classes: 3
  arch: resnet101

args:
  expdir: "."
  logdir: "log/linknet"

stages:

  data_params:
    batch_size: 12
    num_workers: 1
    image_folder: data/img
    mask_folder: data/mask
    fold_csv: data/fold.csv
    fold_number: 0

  state_params:
    num_epochs: 100
    main_metric: &reduce_metric loss
    minimize_metric: False


  criterion_params:
    criterion: BCEDiceLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [100]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: LossCallback
    optimizer:
      callback: OptimizerCallback
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.001