info:
  name: unet
  project: batteries
executors:
  dummy1:
    type: Segmenter
    report: battery-top
    args:
      config: catalyst-config.yml
reports:
  catalyst:
    metric:
      name: loss
      minimize: True

    items:
      _timers/_fps:
        type: series
        key: _timers/_fps
      _timers/data_time:
        type: series
        key: _timers/data_time
      _timers/model_time:
        type: series
        key: _timers/model_time
      _timers/batch_time:
        type: series
        key: _timers/batch_time
      _base/lr:
        type: series
        key: _base/lr
      _base/momentum:
        type: series
        key: _base/momentum
      loss:
        type: series
        key: loss

    layout:
      - type: panel
        title: base
        expanded: False
        row_height: 300
        parent_cols: 3
        items:
          - type: series
            source: _timers/_fps
          - type: series
            source: _timers/data_time
          - type: series
            source: _timers/model_time
          - type: series
            source: _timers/batch_time
          - type: series
            source: _base/lr
          - type: series
            source: _base/momentum
  battery-top:
    extend: catalyst
    metric:
      name: loss
      minimize: True
    items:
      img_classify:
        type: img_classify
        epoch_every: 3
        count_class_max: 100
        threshold:
          anode: 0.1
          cathode: 0.1
    layout:
      - type: panel
        title: main
        table: True
        items:
          - type: series
            source: loss
      - type: panel
        title: classify
        items:
          - type: img_classify
            source: img_classify