info:
  name: first
  project: first
  folder: projects/first
  data_folder: /f/data/first
executors:
  download:
    type: Dummy
    competition: digit-recognizer
#  upload:
#    type: Submit
#    competition: digit-recognizer
#    file: sample_submission.csv
#    depends:
#      - download