info:
  name: mnist_pipe
  project: examples
  type: pipe
pipes:
  infer_valid:
    infer:
      type: infer
      slot: model
      suffix: valid
  infer_test:
    infer:
      type: infer
      slot: model
      suffix: test

interfaces:
  torch:
    batch_size: 512
